#!/bin/bash

# TrustChain Deployment Script
# Deploys Move contracts to Sui testnet/devnet

set -e

echo "🚀 TrustChain Contract Deployment"
echo "=================================="
echo ""

# Check Sui CLI installation
if ! command -v sui &> /dev/null; then
    echo "❌ Sui CLI not found. Please install it first:"
    echo "cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui"
    exit 1
fi

echo "✅ Sui CLI found: $(sui --version)"
echo ""

# Check active address
ACTIVE_ADDRESS=$(sui client active-address)
echo "📍 Active address: $ACTIVE_ADDRESS"
echo ""

# Check balance
echo "💰 Checking balance..."
sui client gas
echo ""

# Build contracts
echo "🔨 Building contracts..."
cd "$(dirname "$0")"
sui move build
echo "✅ Build successful"
echo ""

# Run tests
echo "🧪 Running tests..."
sui move test
echo "✅ Tests passed"
echo ""

# Deploy
echo "🚀 Deploying to network..."
echo "⚠️  This will cost gas. Continue? (y/n)"
read -r CONFIRM

if [ "$CONFIRM" != "y" ]; then
    echo "❌ Deployment cancelled"
    exit 0
fi

DEPLOY_OUTPUT=$(sui client publish --gas-budget 100000000 --json)
echo "$DEPLOY_OUTPUT" > deployment-output.json

# Parse deployment info
PACKAGE_ID=$(echo "$DEPLOY_OUTPUT" | jq -r '.objectChanges[] | select(.type == "published") | .packageId')
CONTRIBUTION_REGISTRY=$(echo "$DEPLOY_OUTPUT" | jq -r '.objectChanges[] | select(.objectType | contains("ContributionRegistry")) | .objectId')
USERNAME_REGISTRY=$(echo "$DEPLOY_OUTPUT" | jq -r '.objectChanges[] | select(.objectType | contains("UsernameRegistry")) | .objectId')

echo ""
echo "✅ Deployment successful!"
echo "========================"
echo ""
echo "📦 Package ID: $PACKAGE_ID"
echo "📋 Contribution Registry: $CONTRIBUTION_REGISTRY"
echo "👤 Username Registry: $USERNAME_REGISTRY"
echo ""

# Create config file for frontend
CONFIG_FILE="../sui-dapp/src/config/contracts.js"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
// Auto-generated by deployment script
// Last deployed: $(date)

export const CONTRACTS = {
  PACKAGE_ID: "$PACKAGE_ID",
  CONTRIBUTION_REGISTRY: "$CONTRIBUTION_REGISTRY",
  USERNAME_REGISTRY: "$USERNAME_REGISTRY",
  NETWORK: "testnet", // Change to "mainnet" for production
};

export const CONTRIBUTION_TYPES = [
  "PULL REQUEST",
  "HACKATHON",
  "DOCUMENTATION",
  "PEER REVIEW",
  "MENTORSHIP",
  "OPEN SOURCE",
  "WORKSHOP",
  "OTHER",
];
EOF

echo "✅ Config file created: $CONFIG_FILE"
echo ""

# Explorer links
EXPLORER_URL="https://suiscan.xyz/testnet/object"
echo "🔍 View on Sui Explorer:"
echo "Package: $EXPLORER_URL/$PACKAGE_ID"
echo "Contribution Registry: $EXPLORER_URL/$CONTRIBUTION_REGISTRY"
echo "Username Registry: $EXPLORER_URL/$USERNAME_REGISTRY"
echo ""

echo "🎉 Deployment complete!"
echo ""
echo "Next steps:"
echo "1. Save these IDs somewhere safe"
echo "2. Update frontend config if needed"
echo "3. Test transactions on explorer"
echo "4. Start building the frontend integration!"
